// src/constants/settings.js

export const DEFAULT_SETTINGS = {
  confidenceThreshold: 0.5,
  nmsThreshold: 0.45,
  filterClass: "all",
};

export const VIDEO_SETTINGS = {
  maxFileSize: 100 * 1024 * 1024, // 100MB
  maxDuration: 120, // 2 minutes in seconds
  supportedFormats: ["mp4", "webm", "avi", "mov"],
  samplingOptions: [
    { value: "all", label: "All frames (highest accuracy)", frames: "all" },
    { value: "5", label: "Every 5 frames (recommended)", frames: 5 },
    { value: "10", label: "Every 10 frames (faster)", frames: 10 },
    { value: "keyframes", label: "Key frames only", frames: "keyframes" },
  ],
};

export const IMAGE_SETTINGS = {
  maxFileSize: 10 * 1024 * 1024, // 10MB
  supportedFormats: ["jpg", "jpeg", "png", "webp", "bmp"],
  targetResolution: { width: 640, height: 640 },
};

export const CLASS_FILTERS = [
  { value: "all", label: "All classes" },
  { value: "people", label: "People only", classes: ["person"] },
  { value: "vehicles", label: "Vehicles only", classes: ["car", "truck", "bus", "motorcycle", "bicycle"] },
  { value: "animals", label: "Animals only", classes: ["dog", "cat", "bird", "horse", "cow", "sheep"] },
];

export const COCO_CLASSES = [
  "person",
  "bicycle",
  "car",
  "motorcycle",
  "airplane",
  "bus",
  "train",
  "truck",
  "boat",
  "traffic light",
  "fire hydrant",
  "stop sign",
  "parking meter",
  "bench",
  "bird",
  "cat",
  "dog",
  "horse",
  "sheep",
  "cow",
  "elephant",
  "bear",
  "zebra",
  "giraffe",
  "backpack",
  "umbrella",
  "handbag",
  "tie",
  "suitcase",
  "frisbee",
  "skis",
  "snowboard",
  "sports ball",
  "kite",
  "baseball bat",
  "baseball glove",
  "skateboard",
  "surfboard",
  "tennis racket",
  "bottle",
  "wine glass",
  "cup",
  "fork",
  "knife",
  "spoon",
  "bowl",
  "banana",
  "apple",
  "sandwich",
  "orange",
  "broccoli",
  "carrot",
  "hot dog",
  "pizza",
  "donut",
  "cake",
  "chair",
  "couch",
  "potted plant",
  "bed",
  "dining table",
  "toilet",
  "tv",
  "laptop",
  "mouse",
  "remote",
  "keyboard",
  "cell phone",
  "microwave",
  "oven",
  "toaster",
  "sink",
  "refrigerator",
  "book",
  "clock",
  "vase",
  "scissors",
  "teddy bear",
  "hair drier",
  "toothbrush",
];
